FROM mirror.gcr.io/library/node:22-alpine
WORKDIR /app

COPY package.json ./
RUN npm install

COPY . .
RUN npm run build

ENV DOCKERFILE_VARIANT=mcp
ENV PORT=3000
ENV HOST=0.0.0.0

EXPOSE 3000
CMD ["npm", "run", "start"]
